language: c
sudo: required
dist: trusty

env:
  global:
        - secure: "nAc3WvwtJBm+hLIYxp4srwgM7qDWRovkEpsza+UITEE8TUqeZND2543xMZlWz1w5qn8V/F/1yX1oYl7Ot0ymmu9Uh41b1NBr3cvo2U8RLDSM9SBoqtyS1pSCnJ2qiSk+hg5GxObWug/ph3TkEgZaDmYCDAgHiv1I9WXVRxeR144="
        - COVERITY_SCAN_BRANCH_PATTERN="(master|coverity-.*)"
        - COVERITY_SCAN_NOTIFICATION_EMAIL="dev@umlaeute.mur.at"
        - COVERITY_SCAN_BUILD_COMMAND="make"
        - LIBSNDFILE_URL="http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.26.tar.gz"

addons:
  apt:
    packages:
      - libvorbis-dev
      - libflac-dev
      - libasound2-dev
      - doxygen
      - lcov
      - ca-certificates

matrix:
  include:
    - compiler: clang
      env:
        - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
    - compiler: gcc
      env:
        - DO_COVERAGE="yes"

install:
  ## build libsndfile
  - mkdir -p libsndfile/build && curl "$LIBSNDFILE_URL" | tar --strip-components=1 -C libsndfile -xvzf -
  - cd libsndfile/build && ../configure --disable-silent-rules && make && sudo make install
  ## remove libtool libs
  - find /usr/local/lib -type f -name "*.la" -exec sudo rm -f {} \+
before_script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./autogen.sh
  - ./configure --disable-silent-rules
  # OMG, Coverity scan uses a certificate not supported by travis-ci
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
  # implement Coverity Scan with before_script instead of addons.coverity_scan
  # to work around too-early quota check by the coverity_scan addon
  - if [[ -n $COVERITY_SCAN_PROJECT_NAME ]] ; then curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true ; fi

script:
- make
- LD_LIBRARY_PATH=/usr/local/lib VERBOSE=1 make distcheck

after_success:
  - if [[ "x${DO_COVERAGE}" = "xyes" ]] ; then LD_LIBRARY_PATH=/usr/local/lib ./coverage.sh; fi
  - if [[ "yes.${TRAVIS_BRANCH}.${TRAVIS_PULLREQUEST}" = "yes.master." ]]; then ./.deploy-documentation.sh ; fi
  - bash <(curl -s https://codecov.io/bash)
